import mongoose from 'mongoose';
const { Schema, model } = mongoose;
const ref = (name, required = true) => ({ type: Schema.Types.ObjectId, ref: name, required, index: true });
const opts = { timestamps: true };
const userSchema = new Schema({ name: String, email: { type: String, unique: true }, password: { type: String, select: false }, resetHash: { type: String, select: false }, resetExpires: Date }, opts);
export const User = model('User', userSchema);
export const Session = model('Session', new Schema({ user: ref('User'), hash: { type: String, unique: true }, expires: { type: Date, expires: 0 } }, opts));
export const Business = model('Business', new Schema({ owner: ref('User'), name: String, city: String, state: String, address: String, phone: String, description: String, notice: String, bankName: String, accountName: String, accountNumber: String, listed: { type: Boolean, default: false }, subscriptionUntil: Date, pricingRevision: { type: Number, default: 0, select: false }, archived: { type: Boolean, default: false } }, opts));
const customerSchema = new Schema({ business: ref('Business'), name: String, phone: String, email: String }, opts);
customerSchema.index({ business: 1, phone: 1 }, { unique: true });
export const Customer = model('Customer', customerSchema);
export const Price = model('Price', new Schema({ business: ref('Business'), category: String, service: { type: String, enum: ['Wash & iron', 'Wash only', 'Iron only'] }, amount: Number, active: { type: Boolean, default: true } }, opts));
export const Photo = model('Photo', new Schema({ business: ref('Business'), data: { type: Buffer, select: false }, mime: String }, opts));
const item = new Schema({ category: String, service: String, quantity: Number, unitAmount: Number, condition: String, photos: [{ type: Schema.Types.ObjectId, ref: 'Photo' }] });
export const STATUSES = ['Dropped off', 'Washing', 'Ironing', 'Ready for pickup', 'Collected'];
export const Order = model('Order', new Schema({ business: ref('Business'), customer: ref('Customer'), reference: { type: String, unique: true }, trackingToken: { type: String, unique: true, select: false }, items: [item], total: Number, dueDate: Date, notes: String, conditionAcknowledged: Boolean, status: { type: String, enum: STATUSES, default: 'Dropped off' }, history: [{ status: String, at: Date, actor: ref('User', false) }] }, opts));
const paymentSchema = new Schema({ business: ref('Business'), order: ref('Order', false), kind: { type: String, enum: ['order', 'subscription'] }, amount: Number, reference: { type: String, unique: true }, status: { type: String, enum: ['pending', 'paid', 'failed'], default: 'pending' }, channel: String, note: String }, opts);
export const Payment = model('Payment', paymentSchema);
export const Expense = model('Expense', new Schema({ business: ref('Business'), supplier: String, description: String, amount: Number, date: Date, method: String }, opts));
